### ISSUE TITLE
Differenza con TorinoTechScene?

### ISSUE THREAD

**Issue by gmacario** [TorinoTech/torinotech.github.io#11]
Ciao,

Oggi ho scoperto http://torinotechscene.it/ con il relativo sito GitHub https://github.com/madbob/torinotechscene.

Entrambe mi sembrano lodevoli iniziative, ma qualcuno e' in grado di spiegarmi la differenza di contenuti e "dove-pubblicare-cosa"?

See also: https://github.com/madbob/torinotechscene/issues/2

**Comment by terrinoni** [comment]
Ciao,
Non conoscevo Torino Tech Scene ma credo siano due fork della stessa idea.

## 

## while(!(succeed = try()));

Marco Terrinoni
http://marcoterrinoni.altervista.org/
Il 12/Gen/2016 15:53, "Gianpaolo Macario" notifications@github.com ha
scritto:

**Comment by gmacario** [comment]
Anch'io l'ho capita cosi', questo ho aperto la stessa issue su entrambi i progetti :-)

A onor del vero il primo commit di https://github.com/madbob/torinotechscene risale al 2015-11-27 (quindi precedente a https://github.com/TorinoTech/torinotech.github.io), ma https://github.com/TorinoTech/torinotech.github.io utilizza una diversa tecnologia (migliore?) per la generazione della pagine.

Comunque la mia vera domanda e' questa: Se entrambi i progetti hanno gli stessi obiettivi non sarebbe piu' furbo cercare di fare un merge dei progetti, anziche' mantenere due liste analoghe?

CC: @grigio, @madbob

**Comment by grigio** [comment]
La storia in breve è questa: qualche giorno prima ho parlato con @madbob che sarebbe bello fare "un aggregatore dei vari eventi open tech di Torino", alla fine abbiamo implementato entrambi l'idea.

Però una differenza sostanziale è che TorinoTech usa Github, ma a differenza di Milano Tech Scene e Torino Tech Scene non richiede l'installazione di alcunché per essere aggiornato. E divide nettamente gli eventi gratuiti da quelli a pagamento

**Comment by madbob** [comment]
La mia versione della storia breve: per un anno più persone mi hanno ripetuto che anche a Torino ci voleva una cosa come [Milano Tech Scene](http://milanotechscene.it/), all'ennesima iterazione ho pubblicato Torino Tech Scene. Ho avuto notizia dell'esistenza di TorinoTech due commit dopo.

Esteticamente TST e' una copia di MST, derivando dallo [stesso template](http://startbootstrap.com/template-overviews/agency/); tecnicamente e' un tantino piu' sofisticato prevedendo, oltre alla [pubblicazione manuale di eventi](https://github.com/madbob/torinotechscene/blob/gh-pages/_posts/2015-12-06-esempio.markdown), un sistema di importazione automatico dei contenuti da Facebook, EventBrite e Meetup.

Personalmente sono gia' in contatto coi responsabili di MST per collaborare su una piattaforma comune, con l'auspicio che *TechScene possa diventare una sorta di "network".

**Comment by grigio** [comment]
La gara di chi ha fatto prima i commit non ha senso: il sito TorinoTech si ispira MTS ma vuole essere molto più facile da aggiornare ed è per questo che l'ho implementato così (da zero e non copiando il codice di MTS).

Secondo me, l'importazione automatica degli eventi è una non-feature perché rischia di inondare il sito di eventi poco pertinenti e poi la pubblicazione manuale fa anche da filtro.

Del network dei network non ne vedo il beneficio visto che ogni città può avere le proprie regole e le proprie sfumature, piuttosto TorinoTech ha già avuto 7PR esterne quindi direi che sta già funzionando...
Tuttavia la piattaforma da utilizzare è secondaria, la sceglieranno le persone che decidono di contribuire attivamente al progetto. L'importante è che ci sia un minimo di coordinamento tra i vari gruppi open \* su dove comunicare gli eventi e, perché no, di organizzarne di eventi comuni quando può aver senso.

Domani sera c'é la [prima cena TorinoTech](http://doodle.com/poll/tzkitthevatgvyma) (siete tutti invitati) e vediamo cosa ne esce.
