### ISSUE TITLE
Hashtags delle tecnologie open source usate nell'evento ?

### ISSUE THREAD

**Issue by grigio** [TorinoTech/torinotech.github.io#14]
Una funzionalità che mi piacerebbe avere è si capisca quasi subito quale/i tecnologie open verranno usate nell'evento a colpo d'occhio.

quindi:

```
..
tags: ["ruby","javascript", "coding"] <-- campo opzionale multiplo, ma caldamente incentivato
```

e il primo tag se è supportato dà il colore all'evento

Esempi di tag:

<X linguaggio di programmazione>
arduino
opendata
openhardware
android

<tag di tipologia evento>
coding
cena
talks
...

Che ne dite?

**Comment by gmacario** [comment]
> Che ne dite?

:+1: - magari con tag verificati su una lista (es. un altro file nel
repository) in modo da evitare il proliferare di tag pseudo-simili?

**Comment by grigio** [comment]
@gmacario non mi è ben chiara quale sia la tua preoccupazione
- Ci saranno dei (macro)tag suggeriti (arduino, linux, nosql, python..) se uno non ne mette o ne mette di altri pazienza
- il primo tag dell'evento, se è "suggerito", avrà anche un colore associato altrimenti non succede nulla

**Comment by gmacario** [comment]
La mia proposta era solo un modo per limitare il numero di tag quasi-uguali o magari con spelling errato.

Comunque direi che la tua proposta di colorare il primo tag tra la lista dei suggeriti mi sembra più che sufficiente.

:+1

**Comment by grigio** [comment]
Chiudo anche questo, tanto non mi pare che abbia senso mettere dei tag per degli eventi che poi vengono rimossi
