### ISSUE TITLE
Verbale 2016-01-14

### ISSUE THREAD

**Issue by carlok** [TorinoTech/torinotech.github.io#15]
- TorinoTech adotterà la formula di TorinoJS: eventi aperiodici composti da tre talk di 25' con 5' di domande ciascuno;
- i talk saranno grossomodo indipendenti da linguaggi specifici, concentrandosi in tre macro aree: metodologie, architetture e infrastrutture;
- l'obiettivo di ciascun talk sarà di presentare un argomento enfatizzandone punti di forza e limiti, favorendo un costruttivo scambio di domande e risposte;
- durante la serata, sono emersi, per possibili talk, i seguenti temi, in ordine alfabetico: si voterà per determinare i tre più interessanti per comporre il panel dei relatori del primo evento.
  - API REST: design patterns;
  - Continuous Delivery: a case study;
  - Jetty: handling HTTP/2 and WebSockets;
  - Kong: a scalable, open source API Layer;
  - Open Whisper Systems: an introduction;
  - OrientDB: a 2nd Generation Distributed Graph Database;
  - Service Discovery in Microservices Architectures

**Comment by gmacario** [comment]
Ciao,

Grazie del verbale. Mi spiace non aver potuto partecipare alla serata, che spero sia stata divertente oltre che utile.

Personalmente sono interessato a praticamente tutti gli argomenti proposti, e confermo la mia disponibilita' a contribuire al panel "Continuous Delivery: a case study", dove avrei in mente di presentare

`<shameless-plug>`
https://github.com/gmacario/easy-jenkins
`</shameless-plug>`

**Comment by carlok** [comment]
Molto interessante! Io ho proposto Kong, peraltro.

**Comment by gibix** [comment]
Anche io non ho potuto esserci, ma mi sembra che la direzione organizzativa sia veramente ottima, penso di essere interessato a quasi tutti i topic, in particolare Open Whisper, API e Jetty. Potrei proporre qualcosa su MQTT o Arduino.

**Comment by carlok** [comment]
Il calendario per le proposte e le votazioni è su https://github.com/TorinoTech/torinotech.github.io/issues/17

**Comment by gmacario** [comment]
Any objections to close?

**Comment by carlok** [comment]
feel free to close it

On Thu, Jun 9, 2016 at 9:12 AM, Gianpaolo Macario notifications@github.com
wrote:

> Any objections to close?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/TorinoTech/torinotech.github.io/issues/15#issuecomment-224817575,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAE845vRBdMb1iAL8rn34FC4FK4GS0w7ks5qJ7zVgaJpZM4HEtEm
> .

## 

Carlo Perassi - http://perassi.org/
