### ISSUE TITLE
+DockerHome Introduzione a Docker e considerazioni in ambito Home Server

### ISSUE THREAD

**Issue by grigio** [TorinoTech/torinotech.github.io#21]
Considerazioni e utili microservices da utilizzare a casa ed eventualmente nel Cloud
Parlerò anche di alcuni container Docker che mi sono sviluppato
https://github.com/grigio/docker-apps

**Comment by carlok** [comment]
+1

**Comment by kenta88** [comment]
+1

**Comment by gmacario** [comment]
+1

**Comment by ffissore** [comment]
+1

**Comment by antonellopasella** [comment]
+1

**Comment by mattiabertorello** [comment]
+1

**Comment by grigio** [comment]
https://speakerdeck.com/grigio/dockers
