### ISSUE TITLE
+Babylon.js Introduzione alla creazione di video game attraverso le webgl

### ISSUE THREAD

**Issue by kenta88** [TorinoTech/torinotech.github.io#22]
Introduzione alle webGl attraverso babylon.js. Guida alla realizzazione di giochi e ambienti 3d senza traumi.

**Comment by pierissimo** [comment]
+1

**Comment by Vincio090** [comment]
+1

**Comment by GuickPa** [comment]
+1

**Comment by ffissore** [comment]
+1

**Comment by antonellopasella** [comment]
+1

**Comment by fradot** [comment]
+1

**Comment by gmacario** [comment]
@kenta88: Per favore metti un link alle slides?

**Comment by grigio** [comment]
@kenta88 grazie per la partecipazione, se metti le slide online linkale anche qui

**Comment by kenta88** [comment]
scusate il ritardo ;)

Le slides sono raggiungibili al seguente link:
http://www.alessiodicrescenzo.com/babylon-talk/#/

Inoltre rispondo in maniera più dettagliata alla domanda che mi è stata posta durante il talk:*\* "Perchè utilizzare babylon o threejs se unity esporta in webgl ?"**

Unity esporta un codice non direttamente accessibile allo sviluppatore, poichè viene automaticamente generato. Questo significa avere un overhead su ogni tipo di fix da apportare, praticamente è necessario ribuildare l'intera applicazione per testare le modifiche apportate. 
Inoltre, i framework js based, permettono un accesso diretto e agevole al dom. In unity abbiamo la possibilità di rispondere agli eventi con nostri handle js, ma questo approccio è parecchio 'macchinoso'. Per esempio basti pensare a un pulsante nel dom che deve triggerare qualcosa nell'ambiente 3d, dobbiamo in pratica controllare sia sul nostro js che l'evento venga triggerato correttamente e sia che sull'applicazione il suo handler funzioni. 
Quindi utilizzare unity o un framework js dipenderà interamente dal tipo di applicazione che si vuole sviluppare e di quanto essa farà uso del Dom e di tutto il mondo js.

Grazie ;)

**Comment by grigio** [comment]
Grazie per le slide e il chiarimento.
