### ISSUE TITLE
+Continuous Delivery di firmware embedded con Docker e Jenkins

### ISSUE THREAD

**Issue by gmacario** [TorinoTech/torinotech.github.io#23]
Alcune esperienze concrete nello sviluppo di firmware per sistemi embedded.

Ho in mente di presentare un esempio utilizzando
- https://github.com/gmacario/easy-build
- https://github.com/gmacario/easy-jenkins

**Comment by carlok** [comment]
+1

**Comment by grigio** [comment]
+1 "firmware embedded" sono argomenti ultra specifici. Il mio suggerimento è se potessi far rientrare anche un discorso più ampio su "Docker su ARM" e tool appositi che sono nati es. https://github.com/resin-io

**Comment by gmacario** [comment]
@grigio: Ottimo suggerimento, sono solo un po' preoccupato del tempo a disposizione (30 min, giusto?)

La mia idea originaria era di presentare l'uso di Docker e Jenkins per controllare l'ambiente di _build_ - piuttosto che il runtime. Sull'uso di Docker come runtime sono altrettanto interessato, purtroppo al momento molto meno esperto.

Posso sicuramente accennare a Docker su ARM, es. http://blog.hypriot.com/ e https://resin.io/, ma secondo me questi altri aspetti meritano una (futura) sessione autonoma, magari quando mi arrivera' il mio prossimo [gadget](https://www.indiegogo.com/projects/turris-omnia-hi-performance-open-source-router#/).

**Comment by gibix** [comment]
+1

**Comment by grigio** [comment]
Si era solo un suggerimento visto i tuoi interessi

**Comment by carlok** [comment]
c'è una certa probabilità di avere due talk su docker: in questo caso sarebbe ancor più importante il suggerimento di Luigi, orientandoti più sulle utilità generali (non tanto "embedded") di Jenkins nel Continuous Delivery... così dovreste evitare di intersecarvi troppo :)

**Comment by gibix** [comment]
Anche a  me piacerebbe vedere qualcosa su Jenkins, magari l'aspetto embedded potrebbe essere semplicemente portato come "esempio" per evitare conflitti.

**Comment by gmacario** [comment]
@gibix, @carlok,

In effetti "firmware embedded" voleva essere solo il pretesto per spiegare come Docker e Jenkins possono venirci in aiuto laddove ci sia la necessita' di:
1. Toolchain controllata e versionata durante tutto il ciclo di vita del progetto
2. Pipeline di build complessa
3. Pipeline distribuibile su piu' nodi per ridurre i tempi di esecuzione

Credo che i concetti e gli esempi possano essere utili anche in altri ambiti, ma visto che la mia esperienza e' prevalentemente nel campo embedded, lascio la risposta al lettore...

**Comment by gmacario** [comment]
Slides pubblicate su https://gmacario.github.io/

Grazie a tutti per la partecipazione!
