### ISSUE TITLE
+MQTTintro Intro to MQTT

### ISSUE THREAD

**Issue by gibix** [TorinoTech/torinotech.github.io#24]
Semplice introduzione su MQTT, specifiche e possibili utilizzi nel campo dell'IoT.

**Comment by grigio** [comment]
+1

**Comment by ffissore** [comment]
+1

**Comment by gmacario** [comment]
+1

**Comment by mattiabertorello** [comment]
+1

**Comment by gmacario** [comment]
Non dovremmo lasciare aperta questa issue?

AFAIK mi ero scambiato con @gbix in modo che lui facesse questa presentazione (che aveva preso più voti della mia, BTW) alla prossima Torino Tech Night.

**Comment by grigio** [comment]
In realtà queste issues erano solo per le votazioni.. quando ci sarà la prossima occasione si ripartirà con il ciclo decisionale https://github.com/TorinoTech/torinotech.github.io#regolamento e quindi tutti candidati partiranno dallo stesso stato di partenza
