### ISSUE TITLE
www.torinotech.it is currently being parked

### ISSUE THREAD

**Issue by gmacario** [TorinoTech/torinotech.github.io#27]
Ciao,

Oggi per sbaglio anziche http://torinotech.it/ ho digitato http://www.torinotech.it/ ottenendo il seguente messaggio di errore:

> This domain name has been registered with Gandi.net
> It is currently being parked by the owner
> See the domain's public registration information

Il sito http://torinotech.it/ invece risponde correttamente.

Forse potrebbe essere opportuno configurare anche www.torinotech.it in modo da servire le pagine di questo repository.

Stando a https://www.gandi.net/whois/details?search=torinotech.it il dominio risulta di proprieta' di Federico Tolomei.

**Comment by grigio** [comment]
bisogna chiedere a @s17t

**Comment by s17t** [comment]
@gmacario, ho impostato il redirect.

**Comment by gmacario** [comment]
Wow!

Grazie @s17t per il rapido fix!
