### ISSUE TITLE
events.yml.txt: Visualizzazione ora eventi di aprile

### ISSUE THREAD

**Issue by gmacario** [TorinoTech/torinotech.github.io#28]
Ciao,

A partire da aprile, gli eventi presenti sul sito http://torinotech.it/ vengono visualizzati con un'ora di differenza rispetto a quanto indicato nel file origine `events.yml.txt`.

Screenshot dal mio browser (Google Chrome Version 48.0.2565.103 m su MS Windows 7 64-bit English)

![capture-20160210-1610](https://cloud.githubusercontent.com/assets/75182/12951063/da237b00-d010-11e5-8d52-52990b137739.PNG)

Estratto da file origine: https://github.com/TorinoTech/torinotech.github.io/blob/master/events.yml.txt#L132-L156

Ipotizzo che il problema sia dovuto al passaggio ad ora legale (2016-03-27)

Non capisco pero' se il problema stia nel testo in `events.yml.txt` oppure nella conversione in HTML.

@grigio: Help, please!

**Comment by gmacario** [comment]
Grazie per il fix!

Magari quando avrò completato il tuo https://corso-javascript.usefedora.com/ lo capirò anch'io :-)

**Comment by grigio** [comment]
qualsiasi fuso orario +1 +2 -5 che dai al parser yaml viene considerato in +1 http://nodeca.github.io/js-yaml/ forzando come formato stringa si riesce ad avere una data più facile da digitare e si riesce a controllare meglio il parsing. Inoltre date yml != js date

![schermata 2016-02-10 alle 22 57 18](https://cloud.githubusercontent.com/assets/8074/12963289/f3e225bc-d049-11e5-8613-8034e4d9d563.png)
