### ISSUE TITLE
README.md: Add a Gitter chat badge

### ISSUE THREAD

**Issue by gmacario** [TorinoTech/torinotech.github.io#38]
Will elaborate as soon as I remember how I managed to have https://github.com/gmacario/wtf-docs/pull/1 (just as an example)

**Comment by grigio** [comment]
se vuoi mettere il badge nel readme fai pure

**Comment by gmacario** [comment]
Please review/merge PR https://github.com/TorinoTech/torinotech.github.io/pull/39

**Comment by gmacario** [comment]
Fix via 5f2ad9120eb8a110688e7c382f7cf750668609b7
