### ISSUE TITLE
Gli eventi non sono visibili sul sito

### ISSUE THREAD

**Issue by sgelob** [TorinoTech/torinotech.github.io#62]

**Comment by grigio** [comment]
È ancora presente il problema? Perché a me non risulta, forse è stato un problema temporaneo

**Comment by gmacario** [comment]
Io li vedo:

![image](https://cloud.githubusercontent.com/assets/75182/26751064/36dce446-4831-11e7-8969-59244c1b4a39.png)

**Comment by sgelob** [comment]
Chrome Version 59.0.3071.61 su Mac

![screen shot 2017-06-04 at 11 12 52](https://cloud.githubusercontent.com/assets/6544108/26760382/dbb73b20-4916-11e7-82f4-ae7875eb4a96.png)

Invece su Safari (sempre Mac) vedo «Invalid Date»

![screen shot 2017-06-04 at 11 15 30](https://cloud.githubusercontent.com/assets/6544108/26760400/32421398-4917-11e7-9a03-ea1f59746841.png)
