### ISSUE TITLE
Dominio in scadenza

### ISSUE THREAD

**Issue by s17t** [TorinoTech/torinotech.github.io#68]
Non sono più disponibile per mantenere il dominio torinotech.it. Il dominio scadrà l'11 Dicembre 2018, il termine ultimo per il rinnovo è 25 Dicembre 2018. 

Sono ovviamente a disposizione per trasferirlo a chi tra @grigio @xrmx @matjack1 @gmacario @antonellopasella ne faccia richiesta.

**Comment by grigio** [comment]
@s17t Grazie per la comunicazione, Per me va bene lasciarlo come torinotech.github.io e comunque c'è https://torinotechscene.it che alla fine è più pratico per le attività ricorrenti. Forse @mukkoo è interessato?

**Comment by matjack1** [comment]
@s17t alla fine com'è andata col dominio? Lo vedo parcheggiato su Gandi.

Tra l'altro scade a fine marzo, se viene lasciato scadere lo potremmo ricomprare se non interessa a nessun altro.

**Comment by s17t** [comment]
L'ultimo rinnovo fatto da me è del  12 Dicembre 2017. Come dal messaggio, visto che nessuno fu interessato lo lasciai scadere. È scaduto quindi il 12 Dicembre 2018. Non ho idea chi se lo sia registrato.

**Comment by matjack1** [comment]
Grazie del feedback @s17t mi chiedevo se per caso ne avessi parlato altrove. Pazienza! Scade di nuovo tra un paio di mesi, vediamo :)
